const router = require("express").Router();
const { auth } = require("../middlewares/auth");
const { asyncHandler } = require("../middlewares/error");
const c = require("../controllers/userController");
router.use(auth);
router.get("/me", asyncHandler(c.me));
router.patch("/me", asyncHandler(c.updateMe));
router.post("/me/password", asyncHandler(c.changePassword));
router.delete("/me", asyncHandler(c.deleteMe));
module.exports = router;
